docs(kms-crypto-key): fix wrong import format
Fixes wrong import format missing location, project name

```
Error: Invalid CryptoKey id format, expecting `{projectId}/{locationId}/{KeyringName}/{cryptoKeyName}` or `{locationId}/{keyRingName}/{cryptoKeyName}, got id: mykeyring/mytoken
```